# 🐼 Pandas - Class 6: GroupBy & Aggregations
Welcome to **Class 6** of our Pandas series. Today we’ll learn how to group data and perform aggregations.

## 1. Concept of Split–Apply–Combine
- **Split** the data into groups based on some criteria.
- **Apply** a function (e.g., sum, mean) to each group.
- **Combine** the results into a new DataFrame or Series.

This is the core idea behind `groupby`.

In [ ]:
import pandas as pd

data = {
    "Employee": [
        "Rahul", "Priya", "Aman", "Neha", "Rohan",
        "Simran", "Kunal", "Anjali", "Arjun", "Pooja",
        "Varun", "Meera", "Sahil", "Kavya"
    ],

    "Department": [
        "IT", "IT", "IT",
        "HR", "HR",
        "Sales", "Sales", "Sales",
        "Finance", "Finance", "Finance",
        "Marketing", "Marketing", "Marketing"
    ],

    "Salary": [
        60000, 75000, 50000,
        45000, 52000,
        40000, 48000, 55000,
        70000, 65000, 72000,
        50000, 58000, 47000
    ],

    "Experience": [
        3, 5, 2,
        2, 4,
        1, 3, 4,
        5, 4, 6,
        3, 4, 2
    ],
    "Age" : [21,22,23,34,21,23,67,75,32,44,19,22,34,54]
}

df = pd.DataFrame(data)

df

   Employee Department  Salary  Experience  Age
0     Rahul         IT   60000           3   21
1     Priya         IT   75000           5   22
2      Aman         IT   50000           2   23
3      Neha         HR   45000           2   34
4     Rohan         HR   52000           4   21
5    Simran      Sales   40000           1   23
6     Kunal      Sales   48000           3   67
7    Anjali      Sales   55000           4   75
8     Arjun    Finance   70000           5   32
9     Pooja    Finance   65000           4   44
10    Varun    Finance   72000           6   19
11    Meera  Marketing   50000           3   22
12    Sahil  Marketing   58000           4   34
13    Kavya  Marketing   47000           2   54

In [ ]:
df["Department"].value_counts()

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

data = {
    "Employee": [
        "Rahul", "Priya", "Aman", "Neha", "Rohan",
        "Simran", "Kunal", "Anjali", "Arjun", "Pooja",
        "Varun", "Meera", "Sahil", "Kavya"
    ],

    "Department": [
        "IT", "IT", "IT",
        "HR", "HR",
        "Sales", "Sales", "Sales",
        "Finance", "Finance", "Finance",
        "Marketing", "Marketing", "Marketing"
    ],

    "Salary": [
        60000, 75000, 50000,
        45000, 52000,
        40000, 48000, 55000,
        70000, 65000, 72000,
        50000, 58000, 47000
    ],

    "Experience": [
        3, 5, 2,
        2, 4,
        1, 3, 4,
        5, 4, 6,
        3, 4, 2
    ]
}

df = pd.DataFrame(data)

df_department_counts = df["Department"].value_counts()
display(df_department_counts)

Department
IT           3
Sales        3
Finance      3
Marketing    3
HR           2
Name: count, dtype: int64

In [ ]:
df[df['Department'] == 'IT']

  Employee Department  Salary  Experience
0    Rahul         IT   60000           3
1    Priya         IT   75000           5
2     Aman         IT   50000           2

In [ ]:
df[df['Department'] == 'IT']['Salary']

0    60000
1    75000
2    50000
Name: Salary, dtype: int64

In [ ]:
df[df['Department'] == 'IT']['Salary'].mean()

np.float64(61666.666666666664)

In [ ]:
df.groupby("Department")['Salary'].mean()
#mean of all 3 department's salary.

Department
Finance      69000.000000
HR           48500.000000
IT           61666.666667
Marketing    51666.666667
Sales        47666.666667
Name: Salary, dtype: float64

In [ ]:
# finding groupby count in each department
df.groupby("Department")['Employee'].count()

Department
Finance      3
HR           2
IT           3
Marketing    3
Sales        3
Name: Employee, dtype: int64

In [ ]:
#aggregation function:
df.groupby("Department")['Salary'].agg(['mean', 'max', 'min'])

                    mean    max    min
Department
Finance     69000.000000  72000  65000
HR          48500.000000  52000  45000
IT          61666.666667  75000  50000
Marketing   51666.666667  58000  47000
Sales       47666.666667  55000  40000

## 2. Using `groupby()` with Aggregation Functions
- Use `groupby('col').mean()` or other functions like sum, count, min, max.
- You can also use `agg()` to pass multiple functions at once.

In [ ]:
#aggregation function:
df.groupby("Department")['Salary'].agg(['mean', 'max', 'min'])

                    mean    max    min
Department
Finance     69000.000000  72000  65000
HR          48500.000000  52000  45000
IT          61666.666667  75000  50000
Marketing   51666.666667  58000  47000
Sales       47666.666667  55000  40000

## 3. Multiple Aggregations on Different Columns
- With `agg()`, you can specify different functions for each column.
- Example: `df.groupby('Dept').agg({'Salary':'mean', 'Age':'max'})`.

In [ ]:
df.groupby('Department').agg({'Salary':'mean', 'Age':'max'})

                  Salary  Age
Department
Finance     69000.000000   44
HR          48500.000000   34
IT          61666.666667   23
Marketing   51666.666667   54
Sales       47666.666667   75

In [ ]:
df.groupby("Department").agg({
    "Salary" : ["mean","max","min"],
    "Age" : ["max","min"]
})

                  Salary               Age
                    mean    max    min max min
Department
Finance     69000.000000  72000  65000  44  19
HR          48500.000000  52000  45000  34  21
IT          61666.666667  75000  50000  23  21
Marketing   51666.666667  58000  47000  54  22
Sales       47666.666667  55000  40000  75  23

## 4. Pivot Tables & Crosstab
- `pivot_table()` summarizes data like Excel pivot tables.
- `crosstab()` shows frequency counts of combinations of factors.
- Both are powerful for summarizing and comparing groups.

In [ ]:
df.pivot_table(values = "Salary",index = "Department")

                  Salary
Department
Finance     69000.000000
HR          48500.000000
IT          61666.666667
Marketing   51666.666667
Sales       47666.666667

In [ ]:
df.pivot_table(values = "Salary",index = "Department",aggfunc='mean')

                  Salary
Department
Finance     69000.000000
HR          48500.000000
IT          61666.666667
Marketing   51666.666667
Sales       47666.666667

In [ ]:
df.pivot_table(values = ["Salary","Age"],index = "Department",aggfunc='mean')

                  Age        Salary
Department
Finance     31.666667  69000.000000
HR          27.500000  48500.000000
IT          22.000000  61666.666667
Marketing   36.666667  51666.666667
Sales       55.000000  47666.666667

In [ ]:
import seaborn as sns

In [ ]:
sns.load_dataset('flights')

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [ ]:
# df.pivot_table(values = "passengers",index = ["year"],columns = 'month',aggfunc='mean')

KeyError: 'passengers'

In [ ]:
# df['AgeGroup'] = pd.cut()

TypeError: cut() missing 2 required positional arguments: 'x' and 'bins'

## Mini Practice
1. Create a DataFrame with columns: Department, Employee, Salary, Age, City.
2. Group by Department to get average Salary and max Age.
3. Apply multiple aggregations using agg().
4. Create a pivot_table to see mean Salary by Department and City.
5. Build a crosstab for Department vs City.

In [ ]:

# 1. Create a DataFrame with columns: Department, Employee, Salary, Age, City

# 2. Group by Department to get average Salary and max Age
# Write your code here

# 3. Apply multiple aggregations using agg()
# Example: mean Salary, max Age per Department
# Write your code here

# 4. Create a pivot_table to see mean Salary by Department and City
# Write your code here

# 5. Build a crosstab for Department vs City
# Write your code here

In [2]:
import pandas as pd

data = {
    "Department": ["IT", "HR", "Finance", "IT", "Marketing", "HR", "Finance", "IT"],
    "Employee": ["Aman", "Riya", "Karan", "Neha", "Rohit", "Pooja", "Arjun", "Simran"],
    "Salary": [60000, 45000, 70000, 65000, 50000, 48000, 72000, 68000],
    "Age": [24, 26, 29, 25, 27, 28, 31, 23],
    "City": ["Delhi", "Mumbai", "Delhi", "Bangalore", "Pune", "Mumbai", "Delhi", "Bangalore"]
}

b = pd.DataFrame(data)

display(b)

  Department Employee  Salary  Age       City
0         IT     Aman   60000   24      Delhi
1         HR     Riya   45000   26     Mumbai
2    Finance    Karan   70000   29      Delhi
3         IT     Neha   65000   25  Bangalore
4  Marketing    Rohit   50000   27       Pune
5         HR    Pooja   48000   28     Mumbai
6    Finance    Arjun   72000   31      Delhi
7         IT   Simran   68000   23  Bangalore

In [11]:
b.groupby("Department").agg({
    "Salary": "mean",
    "Age": max
})

/tmp/ipython-input-1196264258.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  b.groupby("Department").agg({

                  Salary  Age
Department
Finance     71000.000000   31
HR          46500.000000   28
IT          64333.333333   25
Marketing   50000.000000   27

In [4]:
b.groupby("Department").agg({"Salary":"mean","Age":"max"})

                  Salary  Age
Department
Finance     71000.000000   31
HR          46500.000000   28
IT          64333.333333   25
Marketing   50000.000000   27

In [12]:
b.pivot_table(values = "Salary",index = ["Department","City"],aggfunc='mean')

                       Salary
Department City
Finance    Delhi      71000.0
HR         Mumbai     46500.0
IT         Bangalore  66500.0
           Delhi      60000.0
Marketing  Pune       50000.0

In [14]:
pd.crosstab(df["Department"], df["City"])

City        Bangalore  Delhi  Mumbai  Pune
Department
Finance             0      2       0     0
HR                  0      0       2     0
IT                  2      1       0     0
Marketing           0      0       0     1

---
## Summary
- Learned the split–apply–combine concept.
- Used `groupby()` with aggregation functions.
- Applied multiple aggregations to different columns.
- Explored `pivot_table` and `crosstab` for summarizing data.